### ISSUE TITLE
Update gradle?

### ISSUE THREAD

**Issue by nickoneill** [5calls/android#119]
Android studio prompted me to update some gradle files automatically but this causes compilation failures. I'm not sure what the issue is.

I have not checked in the gradle file updates, see if android studio prompts you do upgrade them when you open the project?

**Comment by chadschultz** [comment]
Decided to take a couple minutes to look at it. Fortunately, there were no obvious issues after upgrading Gradle that a build>clean / gradle sync couldn't fix. (in some cases, especially with larger apps, there can be compile errors, runtime errors or inexplicable bad behavior).

To your question, sometimes I'll do the update when prompted by Android Studio - often it's a matter of "do I have time to investigate issues with the upgrade, would it make sense as part of this PR, or should I wait on that?" But yes, sooner or later someone working on the codebase would need to update it - hopefully sooner rather than later.
