### ISSUE TITLE
Google-services.json in source control? 

### ISSUE THREAD

**Issue by Gregliest** [5calls/android#14]
@dektar 

I'm trying to run the project, but I'm getting the error "File google-services.json is missing. The Google Services Plugin cannot function without it."  

Should that file be in source control, or can I use one that I generate [here](https://developers.google.com/mobile/add)?

**Comment by dektar** [comment]
Humm... I left it out of source control because it is what allows this app to identify itself to Google Analytics. Could you try generating one and using it instead, and see if that allows you to run locally? Let me know what happens and we can update the README if it works fine with your new file.

**Comment by Gregliest** [comment]
Cool, it worked.  I'll update the README.

**Comment by dektar** [comment]
Awesome! Thanks for trying that.

**Comment by Gregliest** [comment]
Np.  Is there a Slack channel I should join?  I'd love to discuss where I can be of the most help.

**Comment by nickoneill** [comment]
I believe you should already have an invite @Gregliest

**Comment by magneticflux-** [comment]
@dektar I just stumbled upon this issue through Google, but I believe that the google-services.json file actually should be present. There isn't a security risk because all the information is also included in the .apk distributed to users; the security of the app lies in the signing of the app using a keystore (which should _definitely_ be private). For more details, see [this](https://groups.google.com/forum/#!topic/firebase-talk/bamCgTDajkw) post from a Google developer.
